/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'webonise' at '11/2/16 4:42 PM' with Gradle 2.4
 *
 * @author webonise, @date 11/2/16 4:42 PM
 */

import spock.lang.Specification

class PingAppTest extends Specification{
    def "sayHello returns Hey people"() {
        setup:
        PingApp pingApp = new PingApp()
        when:
        def result = pingApp.sayHello()
        then:
        result == "Hey, people"
    }
}
